### ISSUE TITLE
Remove Py3.4 from 3.x (current stable)

### ISSUE THREAD

**Issue by humitos** [readthedocs/readthedocs-docker-images#91]
Docker is not building the 3.x images anymore because fails on installing something on Py3.4: https://cloud.docker.com/u/readthedocs/repository/registry-1.docker.io/readthedocs/build/hub-builddetail/bfqagmd38q8txumra2dduax

We should remove it or maybe do nothing since this image is about to be deprecated.

**Comment by humitos** [comment]
```
DEPRECATION: Python 3.4 support has been deprecated. pip 19.1 will be the last one supporting it. Please upgrade your Python as Python 3.4 won't be maintained after March 2019 (cf PEP 429).
Collecting pandas
Downloading https://files.pythonhosted.org/packages/08/01/803834bc8a4e708aedebb133095a88a4dad9f45bbaf5ad777d2bea543c7e/pandas-0.22.0.tar.gz (11.3MB)
Installing build dependencies: started
Installing build dependencies: finished with status 'done'
Getting requirements to build wheel: started
Getting requirements to build wheel: finished with status 'error'
Complete output from command /home/docs/.pyenv/versions/3.4.7/bin/python3.4 /home/docs/.pyenv/versions/3.4.7/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_y55zlof:
Traceback (most recent call last):
File "/home/docs/.pyenv/versions/3.4.7/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 207, in <module>
main()
File "/home/docs/.pyenv/versions/3.4.7/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 197, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "/home/docs/.pyenv/versions/3.4.7/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py", line 54, in get_requires_for_build_wheel
return hook(config_settings)
File "/tmp/pip-build-env-wkkdn4xu/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 130, in get_requires_for_build_wheel
return self._get_build_requires(config_settings, requirements=['wheel'])
File "/tmp/pip-build-env-wkkdn4xu/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 112, in _get_build_requires
self.run_setup()
File "/tmp/pip-build-env-wkkdn4xu/overlay/lib/python3.4/site-packages/setuptools/build_meta.py", line 126, in run_setup
exec(compile(code, __file__, 'exec'), locals())
File "setup.py", line 27, in <module>
import versioneer
ImportError: No module named 'versioneer'
----------------------------------------
Command "/home/docs/.pyenv/versions/3.4.7/bin/python3.4 /home/docs/.pyenv/versions/3.4.7/lib/python3.4/site-packages/pip/_vendor/pep517/_in_process.py get_requires_for_build_wheel /tmp/tmp_y55zlof" failed with error code 1 in /tmp/pip-install-9v2l7nlz/pandas
```

Related to #90 since it fails because of `pandas`.

**Comment by humitos** [comment]
Because of this problem, conda is not updated to the latest version #89 :(
